### ISSUE TITLE
markdown formatting, intro

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cudatext_plugins_list#1]
```
Copy plugin directory to _py_ directory that lives alongside CudaText executable. 
```

1. markdown shows it like `_py_`.
2. location of "py" folder is not simple! https://wiki.freepascal.org/CudaText#Location_of_folders_.27settings.27.2C_.27py.27.2C_.27data.27

**Comment by halfbrained** [comment]
Updated, acceptable?

**Comment by Alexey-T** [comment]
yes, thanks.
